### PR TITLE
First kiwix-serve Jmeter test

### LINKED ISSUE #1: Introduce load testing
With Jmeter

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #1

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
This is not sufficiently documented:

- what's the goal of this?
- what does this do?
- what's the required setup?
- what's the expected output?

**Comment by kelson42** [comment]
> * what's the goal of this?

https://en.wikipedia.org/wiki/Software_performance_testing#Load_testing. Here the goal is to secure that under a pre-determined load the kiwix-serve behaves properly.

> * what does this do?

For the moment it tests kiwix-serve only in a basic way:
* Index page
* Few index page apis
* All ZIM loaded
* Fulltext search in a random ZIM
* Suggestion search in a random ZIM

All of this is quite directly (with JMeter) readable/understanable.

> * what's the required setup?

Written in the `README.md`.

> * what's the expected output?

It depends how to use it, but it should be started and run without error.

**Comment by rgaudin** [comment]
This should all be in the README and I see nothing about the expected output there…

Using the provided command:

```
 jmeter -n -t offspot.jmx
WARNING: package sun.awt.X11 not in java.desktop
Creating summariser <summary>
Created the tree successfully using offspot.jmx
Starting standalone test @ Mon Sep 20 09:36:53 GMT 2021 (1632130613680)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary =     17 in 00:00:00 =   56.3/s Avg:     1 Min:     0 Max:    27 Err:    14 (82.35%)
Tidying up ...    @ Mon Sep 20 09:36:54 GMT 2021 (1632130614053)
... end of run
```

And there's a log file that's not much useful.

jmeter GUI is not working properly on my setup (exceptions when selecting “Open”), will try to get that working

**Comment by rgaudin** [comment]
> > * what's the required setup?
> 
> Written in the `README.md`.

Your file seems to expect a kiwix-serve running on localhost at port 8082. That's not in the README.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
